### ISSUE TITLE
リモートハグとローカルハグのクールダウンを別にする

### ISSUE THREAD

**Issue by akaregi** [SiroPlugins/Hugs#1]
リモートハグ： `/hug <player>` で行える遠隔ハグのこと。
ローカルハグ: Shift+右クリのハグ（普通のハグ）のこと。

多分今は両者のハグクールダウンが同じだと思うんですが、これだとリモートハグでハグスパム（コマンドを連打）ができてしまう。なので、ローカルハグとリモートハグを別々のクールダウンにすることで解決しようという魂胆です。

**Comment by Siroshun09** [comment]
リモートハグはそもそもクールダウン設けていません。運営しか使わないという想定で作りましたので。
鯖民にリモートハグを解放するのであれば、config 
 から設定できるようにします。

あと右クリハグにクールダウンがあるのは、意図せず1クリック2,3回ハグする仕様だからです。スパム対策というよりは、その Spigot のイベントが1クリックで2回発火されることの対処の面の方が大きい(だからクールダウン時間の config 設定がない)

**Comment by akaregi** [comment]
設定としてクールダウンを分離できるなら、そうしたほうがいいだろう。

**Comment by Siroshun09** [comment]
分離以前に、
・リモートハグを鯖民に開放するのか
・通常ハグのクールダウンはいじることはあるのか
これで機能追加するかが決まります。

前者は、仮に鯖民に開放しない = 運営しかできない であり、それなら自制だけで対応出来るので、コマンドへのクールダウンは必要ないという結論になります。

後者は将来的にいじることはあっても、そんな頻繁に変えるものでも無いので、コード側で数字変えればいいのではと思います。

**Comment by akaregi** [comment]
> リモートハグを鯖民に開放するのか

プラグイン開発するのに制度のことを考えるのは非常にアレと思うけど、してもいい。

> 通常ハグのクールダウンはいじることはあるのか

ない。クールダウン分離の目的はリモートハグのクールダウンを長くすること。

> コード側で数字変えればいいのではと思います。

ハードコーディングはおすすめしない。

**Comment by Siroshun09** [comment]
今はリモートハグに対して一切のクールダウンを設けていません。
ローカルハグのクールダウンは、リモートハグに一切影響を与えていません。
なので、リモートハグにクールダウンというのは、分離ではなく新設に近いです。

コード側で数字を変えるというのはローカルハグの現在のクールダウンの時間です。
変えるつもりがないなら、ハードコーディングのままでもいいと考えます。

**Comment by akaregi** [comment]
> なので、リモートハグにクールダウンというのは、分離ではなく新設に近いです。

分離でも新設でもどちらでもいい。リモートハグのハグスパムが解決するのが目標だから。

> コード側で数字を変えるというのはローカルハグの現在のクールダウンの時間です。
> 変えるつもりがないなら、ハードコーディングのままでもいいと考えます。

それなら別にリモートハグのクールダウンもハードコーディングでいいんだけど、今後クールダウンいじるってなったときソースからビルドするの**死ぬほど**めんどくない? 私はしたくない。config.yml あたりに設定を委譲すればリロードで済む。

**Comment by Siroshun09** [comment]
そんなに面倒くさいかなぁ....こんなのビルド数秒で終わるし、負担なんてほぼ無いと思いますけど

まぁ、クール時間を config から読み込むのは多分1,2行書くだけなのでまだいいとして、リモートハグへのクールダウンは、ローカルハグのクールダウンコードまるまるコピーする上に、if文足したりなんなりとそっちの方が面倒くさそう。
リモートハグのスパムは鯖負荷は全然かからないしチャット流れるだけなので、別の対応(運営ならお遊びの自制、鯖民なら処罰?)をすれば十分。`/hugs reject` でされた時の自己防衛もできるし、その状態でハグテロしようもんなら、自分だけ被害を被ることになって逆に面白かったり。
つまるところクールダウン設ける意味はあまりないと考えます

**Comment by akaregi** [comment]
> そんなに面倒くさいかなぁ....こんなのビルド数秒で終わるし、負担なんてほぼ無いと思いますけど

`git clone` からやるんだぞ!?

> リモートハグのスパムは鯖負荷は全然かからないしチャット流れるだけなので、別の対応(運営ならお遊びの自制、鯖民なら処罰?)をすれば十分。

だから制度（規制も含む）と開発を一緒くたに(ry

> 自分だけ被害を被ることになって逆に面白かったり。

主観。

> つまるところクールダウン設ける意味はあまりないと考えます

そう……アレだと思うならこのイシュークローズしていいです

**Comment by Siroshun09** [comment]
ローカルクールダウン 実装 (Version 3.2)

> git clone からやるんだぞ!?
Fork してそれを IntellIJ でクローンするだけだと思うんですが....
1分くらいでできるような 🤔 

> だから制度（規制も含む）と開発を一緒くたに(ry
> そう……アレだと思うならこのイシュークローズしていいです
コマンドを仮に規制したとしても、チャットやらなんやらとスパムしようとすればいくらでもできるので、ハグだけクールダウン設けて防止しても、っていう印象です。`/hugs reject` で対応すればいいし、なんなら reject を個人でやれるようにしたほうが良さそう。

> 主観。
ネタにそう言われても。

**Comment by akaregi** [comment]
> Fork してそれを IntellIJ でクローンするだけだと思うんですが....
> 1分くらいでできるような 🤔

それが面倒くさいんですよ……

> コマンドを仮に規制したとしても、チャットやらなんやらとスパムしようとすればいくらでもできるので、ハグだけクールダウン設けて防止しても、っていう印象です

ちょっとコード書いて可能性を排除できるならしたほうがいい。ほっとく必要性を感じない。

> ネタにそう言われても。

ええ……（この文脈でネタはない）

----

自分で言ってることを反故にするようですけど一つ。規制の面において、運営努力で十分解決しうるものを何もしないのはどうかと思うんです。そちらがそう思うならそうとしか言いようがないんですけど……。

----

> まぁ、クール時間を config から読み込むのは多分1,2行書くだけなのでまだいいとして、リモートハグへのクールダウンは、ローカルハグのクールダウンコードまるまるコピーする上に、if文足したりなんなりとそっちの方が面倒くさそう。

私がコード書いてもいいので、面倒くさいと思うなら押し付けてもらって構いません。ただしリポジトリは okocraft に移してもらう（うちの鯖用プラグインなので）。
